### ISSUE TITLE
make init

### ISSUE THREAD

**Issue by abretaud** [usegalaxy-eu/pulsar-infrastructure#2]
Thanks for the fix to #1!
Now I'm doing https://pulsar-network.readthedocs.io/en/latest/build_pulsar_node.html
It says to run `make init` and then `make plan`
If I do it, I get this error during make plan:

```
$ WS=genouest01 make plan
./bin/terraform workspace select genouest01
./bin/terraform validate genouest01

Error: data.template_cloudinit_config.nfs-share: 1 error occurred:
	* data.template_cloudinit_config.nfs-share: file: open /home/abretaud/git/pulsar-infrastructure/genouest01/files/create_share.sh: no such file or directory in:

${file("${path.module}/files/create_share.sh")}
```

and `tree genouest01` gives me this:

```
genouest01
├── exec_nodes.tf
├── ext_network.tf
├── gpu_nodes.tf
├── image.tf
├── int_network.tf
├── key_pair.tf
├── main.tf
├── nfs.tf
├── output.tf
├── pre_tasks.tf
├── providers.tf
├── secgroups.tf
├── tf
│   ├── exec_nodes.tf
│   ├── ext_network.tf
│   ├── files
│   │   └── create_share.sh
│   ├── gpu_nodes.tf
│   ├── image.tf
│   ├── int_network.tf
│   ├── key_pair.tf
│   ├── main.tf
│   ├── nfs.tf
│   ├── output.tf
│   ├── pre_tasks._tf
│   ├── providers.tf
│   ├── secgroups.tf
│   └── vars.tf
└── vars.tf
```

Maybe an error while copying at https://github.com/usegalaxy-eu/pulsar-infrastructure/blob/master/Makefile#L55?
(but it looks strange to overwrite the .tf files prepared in the revious steps !? maybe I'm missing something)

**Comment by gmauro** [comment]
@abretaud I fixed also this. 
Again, better if you can try with a fresh setup. Let me know.

Thanks to be a so kind beta-tester :-D

**Comment by abretaud** [comment]
Great, thanks!
Is it normal that vars.tf is overwritten?

**Comment by gmauro** [comment]
No, it shouldn't. Fixed now.

**Comment by abretaud** [comment]
:+1: thanks it works, vms are running!
